---
- hosts: all
  vars_files: "vars/{{ env }}_vars.yml"
  tasks:
    - name: delete docker content created by Kub
      command: docker rm -f $(docker ps -qa) && docker rmi -f $(docker images -q) && docker volume rm $(docker volume ls -q)

    - name: unmount partitions created by Kub
      command: for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher; do umount $mount; done

    - name: clean up directories
      command: "rm -rf {{ item }}"
      loop: "{{ directories_to_clean }}"

    - name: Attempting reboot
      shell: reboot
      async: 1200
      poll: 0

    - name: Waiting for resurection
      wait_for_connection:
        delay: 60
        timeout: 300
