---
- hosts: all
  vars_files: "vars/{{ env }}_vars.yml"
  tasks:
    - name: delete docker content created by Kub
      shell: "docker rm -f $(docker ps -qa) && docker rmi -f $(docker images -q) && docker volume rm $(docker volume ls -q)"
      ignore_errors: yes

    - name: get list of mounted path
      shell: "mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher"
      register: list_mounted_path

    - name: display registered variable
      debug:
        msg: "{{ item }}"
      loop: "{{ list_mounted_path.stdout_lines }}"

    - name: clean up directories
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ directories_to_clean }}"

    - name: Attempting reboot
      shell: reboot
      async: 1200
      poll: 0

    - name: Waiting for resurection
      wait_for_connection:
        delay: 60
        timeout: 300
